training:
  logging_dir: '/user/vgaraujo/storage/CPC-NLP-PyTorch/logs'
  log_interval: 100
  epochs: 10
  batch_size: 64
  no_cuda: False
  multigpu: False
  seed: 42
  resume_name: False
comet:
  api_key: '6oPfzhw55BucwZ4m8rV62ppyw'
  previous_experiment: False
dataset:
  books_path: '/user/vgaraujo/storage/Datasets/BookCorpusReady'
  vocab_name: 'vocab_cpc'
  vocab_size: 20000
  window: 9
  max_sen_length: 32
  do_lower_case: True
  padding_idx: 0
  unknown_idx: 1
  mini_dataset: False
cpc_model:  
  k_size: 3
  emb_dim: 620
  ar_type: 'gru'
  ar_dim: 2400
  enc_type: 'cnn'
  enc_dim: 2400
  